name = "bidsentra-contact-form"
main = "src/index.ts"
compatibility_date = "2026-03-27"

[vars]
BREVO_SENDER_NAME = "BidSentra"
BREVO_SENDER_EMAIL = "info@bidsentra.pl"
BREVO_RECEIVER_EMAIL = "info@bidsentra.pl"
ALLOWED_ORIGINS = "https://bjd1988.github.io,https://bidsentra.pl,https://www.bidsentra.pl,http://localhost:3000"
BREVO_AUTOREPLY_TEMPLATE_ID = "1"
